### ISSUE TITLE
Missing file: hp4600consts.h

### ISSUE THREAD

**Issue by gaborwho** [Triften/hp4600#1]
Hello,
Thank you for the great tool, my scanner would have been useless under Linux without your effort!
I tried to compile the executable, but it's missing the following file:
hp4600consts.h

**Comment by OlavGullaksen** [comment]
Hello,
I have the same problem with the missing hp4600consts.h file when trying to compile.

I think as well the compiling commands have to be updated with the change of file names in the GitHub folder:
hp4600-scanfullpage11.c -> hp4600-scanfullpage.c
and
fixhp4600output -> fixhp4600output-new

??

**Comment by Triften** [comment]
I added the missing header file and updated the README.
