### ISSUE TITLE
missing usb.h

### ISSUE THREAD

**Issue by gun777** [Triften/hp4600#2]
Hi
hp4600scanfulfile says #include usb.h
even in libusb-1.0.20 there is no such file
Ubuntu 14.04 LTS
thank you

**Comment by rdpate** [comment]
gun777: The readme says a legacy libusb is required; however, it works for me with libusb-dev 2:0.1.12 on Ubuntu 16.04.

**Comment by Triften** [comment]
@gun777 Thanks for giving this a spin! Sorry I haven't paid attention to this repo in the intervening years (I haven't owned this scanner for some time now.) I hope you were able to pull the old libusb-devel and get some use out of it.
