### ISSUE TITLE
Runtime Error: Scan died! (Error 32512)

### ISSUE THREAD

**Issue by Destroyer47** [Triften/hp4600#3]
Hello @Triften,

Firstly, I'd like to congratulate you as **THE ONLY** developer whose software works with this machine at all, since HP took down their Winblows drivers and pulled support entirely, which effectively would make this scanner a literal paper weight.
Anyway, I've managed to compile the code and get it running, but hitting the scan button results in a 32512 error and fails to scan.

Here's what my terminal's output reads:
```
[destroyer47@Ryzen3600 hp4600]$ perl hp4600scan

/mnt/sda1/BuildFiles/hpScanJet4600Drivers/hp4600/Default.bmp

Tk::Error: Scan died! (Error 32512)

 main::scanimg at hp4600scan line 118

 Tk callback for .frame.button

 Tk::__ANON__ at /usr/lib/perl5/5.34/vendor_perl/Tk.pm line 251

 Tk::Button::butUp at /usr/lib/perl5/5.34/vendor_perl/Tk/Button.pm line 175

 <ButtonRelease-1>

 (command bound to event)

Usage $widget->update(...)

MainWindow=HASH(0x563a532cc4d8) is not a Tk object at hp4600scan line 67.

```
~I have no clue as to where this error is even generated, since it's not in the source code and nothing pops up in any search results for this. (edit: I've found where there error value is generated*, and it appears related to the system function call in the perl script.)
Any insight into this issue is very much appreciated, since I really don't want to try hacking a new programmable logic board onto this scanner just to scan documents if possible.~ Solved using the solution in Edit 3.

*the code:
```
        #$main->Label(-text => 'Scanning to '.$tempfile.'...')->pack;
	$main->update;
	select(undef,undef,undef,0.50); # sleep half second
	$busy = 1;
	$error = system('gksudo '.$scriptpath.'hp4600scanfullfile '.$tempfile.' >/dev/null 2>/dev/null');
	$busy = 0;
	#$main->Label(-text => $error)->pack;
	if($error){
		$statusline = 'Scan died! Error '.$error;
		die "Scan died! (Error $error)\n";
	}
```
Edit 2: Apparently, the `gksudo` command is long deprecated due to security issues, and therefore needs to be replaced with its modern day equivalent, `pkexec`.
Edit 3: Using using `pkexec` as a drop in for `gksudo` in that all-in-one script file actually works fantastically. I suggest adding this 1 step fix to the repo. The one issue with this fix is that it will ask for root login twice; once for running the scan and second for patching the image.

**Comment by Triften** [comment]
Thanks for giving this a spin! Sorry I haven't paid attention to this repo in the intervening years (I haven't owned this scanner for some time now.) It sounds like this is mostly sorted out and/or the perl/tk script is succumb to bitrot.
